# make_ats_sprites.ps1 -- turn the two ATS sprites into a C header the injected DLL can use.
#
# The DLL draws inside the game's own present, which happens on the render thread with no COM
# apartment of its own and no room to be loading files. So the pixels are baked in: premultiplied
# BGRA, top-down, exactly the shape AlphaBlend wants, with nothing left to decode at runtime.
#
# Run after replacing either PNG:
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\make_ats_sprites.ps1

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
$assets = Join-Path $root 'src\Login38.App\Assets\Ats'
$out = Join-Path $root 'native\ddraw_inproc\src\ats_sprites.h'

function Convert-Sprite([string]$file, [string]$name) {
    $bitmap = [System.Drawing.Bitmap]::FromFile($file)
    try {
        $rect = New-Object System.Drawing.Rectangle 0, 0, $bitmap.Width, $bitmap.Height
        $data = $bitmap.LockBits(
            $rect,
            [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
            [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        try {
            $count = $data.Stride * $bitmap.Height
            $bytes = New-Object byte[] $count
            [System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $bytes, 0, $count)
        }
        finally {
            $bitmap.UnlockBits($data)
        }

        # Straight alpha out of the file, premultiplied here. AlphaBlend with AC_SRC_ALPHA reads
        # the colour channels as already multiplied, and handing it straight alpha is the classic
        # way to get a bright halo around everything.
        $text = New-Object System.Text.StringBuilder
        [void]$text.AppendLine("#define ${name}_W $($bitmap.Width)")
        [void]$text.AppendLine("#define ${name}_H $($bitmap.Height)")
        [void]$text.AppendLine("static const unsigned char ${name}[] = {")

        for ($y = 0; $y -lt $bitmap.Height; $y++) {
            $row = New-Object System.Text.StringBuilder
            for ($x = 0; $x -lt $bitmap.Width; $x++) {
                $i = ($y * $data.Stride) + ($x * 4)
                $a = $bytes[$i + 3]
                $b = [int](($bytes[$i] * $a + 127) / 255)
                $g = [int](($bytes[$i + 1] * $a + 127) / 255)
                $r = [int](($bytes[$i + 2] * $a + 127) / 255)
                [void]$row.Append("$b,$g,$r,$a,")
            }
            [void]$text.AppendLine($row.ToString())
        }

        [void]$text.AppendLine('};')
        return $text.ToString()
    }
    finally {
        $bitmap.Dispose()
    }
}

$lines = @(
    '// ats_sprites.h -- generated by tools/make_ats_sprites.ps1. Do not edit.',
    '//',
    '// The two sprites out of the classic client ATSMsgHudLayout.csb, as premultiplied BGRA',
    '// (top-down), which is what AlphaBlend takes without further work.',
    '#pragma once',
    ''
)

$header = New-Object System.Text.StringBuilder
foreach ($line in $lines) { [void]$header.AppendLine($line) }
[void]$header.Append((Convert-Sprite (Join-Path $assets 'Common_ATS_Ico_Ing_01.png') 'ATS_LETTERS'))
[void]$header.AppendLine()
[void]$header.Append((Convert-Sprite (Join-Path $assets 'Common_ATS_Ico_Ing_02.png') 'ATS_RING'))

[System.IO.File]::WriteAllText($out, $header.ToString(), (New-Object System.Text.ASCIIEncoding))
Write-Host "[OK] $out"
